AZURE_OPENAI_ENDPOINT = "https://sonderwestus.openai.azure.com/openai/deployments/dev-gpt-4o-mini/chat/completions?api-version=2024-08-01-preview"
AZURE_OPENAI_KEY = "d7817408215242db91a1fea3b2bbc95c"